<div style="background-color: #90EE90;">   <b>NIKITA CHHETRI</b>  </div>

#### This notebook contains scenario-based Python questions along with their solutions. It covers topics such as Python basics, data structures, NumPy, pandas, and data types.


In [1]:
import numpy as np
import pandas as pd
#importing necessary libraries

Scenario: You have a list of integers, and you need to find the maximum value in the list.

1) How would you find the maximum value from the following list?


In [2]:
list =np.array([3,6,7,9,10])
#created an array of the list 
list.max()
#applied max method to search largest element

10

Scenario: You need to concatenate a list of strings into a single string, with each string separated by a comma.

2) How would you combine the following list of strings into a single string?


In [3]:
string= ['NIKI','LASXMI','Resma','MONICA']
stri = ''
for name in string:
    stri += name + ','
    stri = stri[:-1]
stri

'NIKILASXMIResmaMONICA'

In [4]:
names = ['Rahul','Sema','Shiv','Shankar','Jessie','Rizma']
combined_string = ''
#using loop method
for name in names:
    combined_string += name + ','
combined_string = combined_string[:-1]
#difference lies here although the codes are exactly same,indentation changed the result entirely
combined_string


'Rahul,Sema,Shiv,Shankar,Jessie,Rizma'

Scenario: You have a dictionary where the keys are names and the values are ages. You need to retrieve the age of a specific person.

3) How would you get the age of "Dev" from the following dictionary?


In [5]:
name_age = {'Rema':35,'Daksh':27,'Ritvik':32,'Samy':25}
name_age['Ritvik']
#used index to retrieve the age


32

Scenario: You need to remove duplicate elements from a list while preserving the original order of elements.

4) How would you remove duplicates from the following list?


In [6]:
duplicates = [1,2,4,4,6,8]
unique=[]
#an empty cell to fill in with unique elements
for duplicate in duplicates:
    if duplicate not in unique:  #nested loop
        unique.append(duplicate)
unique

[1, 2, 4, 6, 8]

Scenario: You have a NumPy array and need to compute the sum of all its elements.

5) How would you find the sum of elements in the following NumPy array?


In [7]:
array = np.array([1,2,3,4,5])
total_sum = np.sum(array)
#used np.sum() function to get the sum
total_sum


15

Scenario: You have a 2D NumPy array and need to get the maximum value from each column.

6) How would you find the maximum values for each column in the following array?


In [8]:
two_d = np.array([[3,4,5],[8,6,5],[0,9,5]])
two_d
np.max(two_d, axis = 0)
#np.max gives us the maximum value 
#axis=0 represents the columns


array([8, 9, 5])

Scenario: You have a DataFrame and need to sort it by a specific column.

7) How would you sort the DataFrame by the "Age" column?


In [9]:
data = {'Name':['Rahul','Sema','Shiv','Shankar','Jessie','Rizma'],
       'Age':[25,34,68,23,45,21]}
#created a variable data and converted into df dataframe
df = pd.DataFrame(data)
df.sort_values(by='Age')
#sort_values to sort data 


Name  Age
5    Rizma   21
3  Shankar   23
0    Rahul   25
1     Sema   34
4   Jessie   45
2     Shiv   68

Scenario: You need to calculate the total sum of a column in a DataFrame.

8) How would you find the sum of the "Sales" column?


In [10]:
groceries = {'Product':['Apple','Banana','Grapes','Orange'],
             'Sales':[150,200,125,356]}
sales_data = pd.DataFrame(groceries)
total_sales = sales_data['Sales'].sum()
# sales_data['Sales'] represents the sales column on which summation is being 
# carried out
total_sales


831

Scenario: You need to check if a variable is of type int.

9) How would you verify if a variable x is an integer?


In [11]:
num = 3
# using if else method(conditional statement)
if type(num) is int:
    print(num, "is an integer")
else:
    print(num, "is not an integer")


3 is an integer


Scenario: You have a list of mixed types and need to create separate lists for integers, floats, and strings.

10) How would you categorize the following mixed list into different types?



In [12]:
mixed = [1,'hi',2.3,'Liza',4]
integers = []
floats =[]
strings = []
#created empty variables to fill in with respective type
for i in mixed:
    if type(i) is int:    #need to be careful about indentations
        integers.append(i)
    elif type(i) is float:
        floats.append(i)
    else:
        strings.append(i)
        
print('Integers:',integers)
print('Floats:',floats)
print('Strings:',strings)


Integers: [1, 4]
Floats: [2.3]
Strings: ['hi', 'Liza']


Scenario: You are given a string of comma-separated numbers. You need to convert this string into a list of integers.

11) How would you achieve this conversion?



In [13]:
csv_string = '1,2,4,6'
in_t = csv_string.split(",")
#split to split the numbers using ',' delimiter
in_t = [int(num) for num in in_t]
#int(num) to convert the type of number in the in_t list
#code is inside [], as we are creating a list
in_t


[1, 2, 4, 6]

Scenario: You need to reverse the words in a sentence while keeping the order of the words intact.

12) How would you reverse each word in the following sentence?



In [14]:
sentence = 'My name is nikita'
sentence[::-1]
#reversing using indexing

'atikin si eman yM'

In [15]:
sentence1 = 'My name is nikita'
reverse_sentence = sentence1[::-1] #reversing the sentence
reversee=" ".join(reverse_sentence) #Joining the characters using space
reversee


'a t i k i n   s i   e m a n   y M'

Scenario: You need to combine two lists into a dictionary where the elements of the first list are keys and the elements of the second list are values.

13) How would you combine the following lists into a dictionary?


In [16]:
name = ['Lexa','John','Wesley']
Age = [45,32,23]

dictionary = {}
for i in range(len(name)):
    dictionary[name[i]]=Age[i]
dictionary
#creates a sequence for name 0,1,2 and assigns value acc using same indexing for 2nd list
#if 0th name is pulled simultaneoulsy 0th age is pulled


{'Lexa': 45, 'John': 32, 'Wesley': 23}

Scenario: You are given a list of tuples where each tuple contains a name and an age. You need to sort this list by age.

14) How would you sort the following list of tuples by age?



In [17]:
tuples = [('Lexa',45),('George',56),('Ravi',34)]
# Sorting the list of tuples by age 
people = sorted(tuples)
people

[('George', 56), ('Lexa', 45), ('Ravi', 34)]

In [18]:
tupless = [('Lexa',45),('George',56),('Ravi',34)]
sorted_people = sorted(tupless, key=lambda x: x[1])
sorted_people
#key=lambda x: x[1] is a sort function, where lamda x is a function that takes 1 argument,
#while x[1](index) represents 2nd part of tuple

[('Ravi', 34), ('Lexa', 45), ('George', 56)]

In [19]:
tuplesss = [('Lexa',45),('George',56),('Ravi',34)]
sorted_peoplee = sorted(tupless, key=lambda x: x[0])
sorted_peoplee

[('George', 56), ('Lexa', 45), ('Ravi', 34)]

Scenario: You have a 2D NumPy array and need to calculate the mean value of each row.

15) How would you compute the mean value for each row in the following array?


In [20]:
means = np.array([[1,2,3],[4,5,6],[7,8,9]])
mean = np.mean(means,axis = 1)
#np.mean() function calculates mean for each rows (axis=1)
mean


array([2., 5., 8.])

Scenario: You need to create a NumPy array of size 10 filled with zeros, and then set the fifth element to 5.

16) How would you create and modify the array as described?



In [21]:
zero_s = np.zeros(10)
zero_s[4]=5 #replacing the value with the index location
zero_s


array([0., 0., 0., 0., 5., 0., 0., 0., 0., 0.])

Scenario: You have a DataFrame and need to find the median of a numeric column

17) How would you find the median of the "Scores" column in the following DataFrame?



In [22]:
dff = {'Name':['Rahul','Sema','Shiv','Shankar','Jessie','Rizma'],
       'Scores':[25,34,68,23,45,21]}
media_n = pd.DataFrame(dff)
media_n['Scores'].median()
#media_n['Scores'] represents the Scores column 


29.5

Scenario: You need to filter rows where the value in the "Sales" column is above 100 and then sort these rows by "Date" in descending order.

18) How would you filter and sort the DataFrame based on the given criteria?



In [23]:
rows = {'Product':['Apple','Banana','Grapes','Orange'],
        'Sales':[150,200,125,56],
       'Date':['2024-10-09','2024-10-11','2024-11-06','2024-12-12']}
data = pd.DataFrame(rows)
filter_data =data[data['Sales'] > 100]
#this variable gives sales above 100
filter_data.sort_values(by='Date',ascending = False)


Product  Sales        Date
2  Grapes    125  2024-11-06
1  Banana    200  2024-10-11
0   Apple    150  2024-10-09

Scenario: You have a string containing a number and need to convert it to an integer. Additionally, handle the case where the string might not represent a valid integer.

19) How would you safely convert the string "42" to an integer and handle invalid cases?



In [24]:
string_number = "42"
if string_number:
    integer_value = int(string_number)
    print("The integer value is:", integer_value)
else:
    print("The string is not a valid integer")


The integer value is: 42


Scenario: You have a list containing different data types, and you want to separate out all the strings.

20) How would you extract all string elements from the following list?



In [25]:
mixe_d = [2,'hey',3,3.4,True]
strings = [] 
for item in mixe_d:
    if type(item) == str:
        strings.append(item)

print(strings)
 

['hey']
